#!/bin/bash
# Upload and Deploy Model to Server
# Replace YOUR_USER and YOUR_SERVER with your actual credentials

echo "Step 1: Upload tarball to server"
echo "Run this command (replace YOUR_USER@YOUR_SERVER):"
echo ""
echo "scp minilm_model.tar.gz YOUR_USER@YOUR_SERVER:/var/www/gift-intelligence/"
echo ""
echo "----------------------------------------"
echo ""
echo "Step 2: SSH into server and run these commands:"
echo ""
echo "ssh YOUR_USER@YOUR_SERVER"
echo ""
echo "cd /var/www/gift-intelligence/"
echo ""
echo "# Backup old model (if exists)"
echo "mv minilm_full_dimension_models minilm_full_dimension_models.backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null"
echo ""
echo "# Extract new model"
echo "tar -xzf minilm_model.tar.gz"
echo ""
echo "# Verify file size (should be 87M)"
echo "ls -lh minilm_full_dimension_models/minilm_model/model.safetensors"
echo ""
echo "# Verify checksum (should be 8f81813590a796d3e896676c8aa0af7d)"
echo "md5sum minilm_full_dimension_models/minilm_model/model.safetensors"
echo ""
echo "# Set correct permissions"
echo "chmod -R 755 minilm_full_dimension_models/"
echo ""
echo "# Clean up tarball"
echo "rm minilm_model.tar.gz"
echo ""
echo "# Restart service (adjust service name if needed)"
echo "sudo systemctl restart embedding-service"
echo "# OR if using uvicorn directly:"
echo "# pkill -f 'uvicorn app_embedding_service' && uvicorn app_embedding_service:app --host 0.0.0.0 --port 8000 &"
